

const faqData = [
        {       
         subjectTitle:'FAQs', 

        subjectTopics: [
            'About Pomodoro Crush',
            'The Pomodoro Method',
            'Development',],

        subjectQuestions : [
            [
                'What is Pomodoro Crush?',
                'What makes Pomodoro Crush Different?',
                `How should I use this?`
            ],
            [
                'What is a Pomodoro?', 
                'How does a Pomodoro work?', 
                'What are the benefits?',
            ],
            [
                'Who Made This?',
                'What are some future updates?',
            ],
        ], 
        subjectAnswers: [
            [
                `Pomodoro Crush is a gamified productivity tool that combines the focus of a Pomodoro app with the simple organization of a todo list.`,
                `Pomodoro Crush specializes in deep, deliberate focus applied to larger tasks.`,
                 `First decide on the amount of time(Pomodoros) you would like to spend every day. Then create tasks in the Todo List component. 
                 Choose how long you would like to work on these tasks (Add Pomodoros). It's best to find the right balance. Too many Pomodoros, 
                 and you'll burn out. Too little and you might loose interest. Once you find the right balance, begin to gradually increase
                 that amount over time. Build your focus as if it were a bicep.`,
            ],
            [
                `A Pomodoro is a productivity technique designed to break down any large task into short, timed intervals.`,

                `The user dedicates a given amount of time (usually 25 minutes) to focus on a single task without interuption, then takes a break (5 minutes).`,

                `The Pomodoro Technique helps the user work their focus muscles by demanding that they give a task their undivided attention.
                Also, by breaking tasks down into smaller chunks, the practitioner is less likely to procrastinate`,
            ],
            [
                `Hi, my name is Jordan Lesich and thanks for taking the time to learn about Pomodoro Crush. Like pretty much everyone who frequently uses a computer 
                or phone, I've fought a hard-won battle with focus and procrastination. My goal is to create technologies that help people act on their greatest ambitions
                by freeing them from meaningless distractions.`,
                `This is a protoype version in its early stages of development. There are many planned upgrades on the way. Much of this will be generated by user 
                feedback. I'd like to spend time deepening the gamification system, making the user experience more customizable, and building an entire a suite of 
                tools geared to helping people get things done`,
            ],
            ],
        },
        {       
        subjectTitle:'Game Rules', 

        subjectTopics: [
                    'Rules',
                    'Gamification',
                    'Planned Upgrades'
                    ],

        subjectQuestions : [
            [
                'Objective',
                'Points',
                'How does a player earn points?',
                `Crush Power`,
                `Does Crush Power reset like points?`,
                `Strategy`,
            ],

            [
                'What is gamification?', 
                'How will Gamification help me?'
            ],
            [
                'Levelling UP', 
            ],
        ], 
        subjectAnswers: [

            [
                `The key objective of Pomodoro Crush is to get quality, focused work done every day.`,

                `In Pomodoro Crush, the points are a marker of daily progress. Every night the points reset, 
                giving the user a shot at a new high score. `,

                'The player recieves 100 points for each Pomodoro completed. They can increase this amount by increasing their Crush Power',

                `Crush Power is a bonus system designed to enforce consistency. The amount of Crush Power is added onto each Pomodoro. 
                Players recieve Crush Power for finishing Pomodoros and bonuses for finishing tasks.`, 

                `If the player has finished all their tasks, then they get to carry their Crush Power over into the next day. If there are still tasks
                left over by midnight, then the score resets to zero`,

                `In order to get the highest score possible, choose an amount of Pomodoros you would like to spend working on each day. 
                Then choose what to spend that time on. It's best to find the right balance. Too many Pomodors, and you'll burn out. Too little
                and you might loose interest. Once you find the right balance, begin to gradually increase that amount over time`,
            ],

            [
                `Gamification is a design approach that adds game elements to non-game systems, mostly to increase motivation and enhance usability.`,
                `All too often the goals we wish to achieve yield little short term benefits. Gamification seeks to bridge that gap by awarding superficial 
                short-term rewards that can help signify progress.`
            ],
        
            [
                `In the next update, players will recieve a higher Crush Power multiplyer for each successful day in a row. In addition to that, players will
                 be able to spend hard-earned Crush Points for a higher level, which will generate more Crush Points, giving an even bigger advantage to those
                 who are consistent.`,
            ]
            ],
        },
]


export {faqData}